exports.prefixRoll = "&roll "
exports.prefixReRoll = "&reroll "
exports.prefixInfo = "&info"
exports.prefixMap = "&map"
exports.prefixHelp = "&help"
exports.prefixDeck = "&deck"
exports.prefixInit = "&init"
exports.prefixSave = "&save"
exports.prefixDuel = "&duel"

exports.prefixInitDuelliste = "&initduelliste"
exports.prefixAddCard = "&addcard"

exports.prefixInventory = "&bn"
exports.prefixQuest = "&quest"